### ISSUE TITLE
投稿削除→エラー発生

### ISSUE THREAD

**Issue by takaykuki0310** [takaykuki0310/twitter_app#5]
1度目のクリック
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):

app/controllers/posts_controller.rb:59:in `destroy'

2度目のクリック

NoMethodError (undefined method `destroy' for nil:NilClass):
app/controllers/posts_controller.rb:55:in `destroy'

3度目
投稿が削除されずにトップ画面に遷移

**Comment by takaykuki0310** [comment]
解決

**Comment by takaykuki0310** [comment]
if のつけ忘れと,before_actionによる遷移のエラー
解決
